In [3]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, accuracy_score, precision_score,confusion_matrix

In [4]:
df = pd.read_csv("../datasets/Cleaned_Customer_Churn.csv")

In [5]:
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Gender_Female,Gender_Male,Geography_France,Geography_Germany,Geography_Spain,Exited
0,619,42,2,0.00,1,1,1,101348.88,1,0,1,0,0,1
1,608,41,1,83807.86,1,0,1,112542.58,1,0,0,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,1,0,0,1
3,699,39,1,0.00,2,0,0,93826.63,1,0,1,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,1,0,0,0,1,0

In [6]:
X = df.drop("Exited",axis=1)

In [7]:
Y = df['Exited']

In [8]:
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Gender_Female,Gender_Male,Geography_France,Geography_Germany,Geography_Spain
0,619,42,2,0.00,1,1,1,101348.88,1,0,1,0,0
1,608,41,1,83807.86,1,0,1,112542.58,1,0,0,0,1
2,502,42,8,159660.80,3,1,0,113931.57,1,0,1,0,0
3,699,39,1,0.00,2,0,0,93826.63,1,0,1,0,0
4,850,43,2,125510.82,1,1,1,79084.10,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,1,1,0,0
9996,516,35,10,57369.61,1,1,1,101699.77,0,1,1,0,0
9997,709,36,7,0.00,1,0,1,42085.58,1,0,1,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,0,1,0,1,0
9999,792,28,4,130142.79,1,1,0,38190.78,1,0,1,0,0

In [9]:
Y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [10]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.2,random_state=42)

In [11]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
X_train

array([[ 0.35649971, -0.6557859 ,  0.34567966, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.29493847, -0.3483691 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213, -1.41636539, -0.69539349, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -0.08535128, -1.38944225, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.3900109 ,  1.03972843, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  1.15059039, -1.38944225, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(8000, 13))

In [13]:
logistic = LogisticRegression()

In [14]:
logistic.fit(X_train,Y_train)

LogisticRegression()

In [70]:
Y_pred = logistic.predict(X_test)

In [73]:
Y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(2000,))

In [75]:
ypred = pd.DataFrame(Y_pred)

In [77]:
ypred.value_counts()

0
0    1857
1     143
Name: count, dtype: int64

In [16]:
accuracy_score(Y_test,Y_pred)

0.811

In [17]:
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.83      0.96      0.89      1607
           1       0.55      0.20      0.29       393

    accuracy                           0.81      2000
   macro avg       0.69      0.58      0.59      2000
weighted avg       0.78      0.81      0.77      2000

In [18]:
confusion_matrix(Y_test,Y_pred)

array([[1543,   64],
       [ 314,   79]])

In [19]:
precision_score(Y_pred,Y_test)

0.2010178117048346

In [20]:
import pickle

In [25]:
with open("../models/logisticmodel.pkl","wb") as f:
    pickle.dump(logistic,f)

In [26]:
with open("../models/logisticmodel.pkl","rb") as f:
    logi = pickle.load(f)

In [120]:
# sample = pd.DataFrame([[789,26,7,80333,5,1,1,7000000,1,0,0,0,1]])
sample = pd.DataFrame([[165,56,3,11190333.00,1,1,1,1551348.88,1,0,1,0,0]])

In [121]:
sample

    0   1   2           3   4   5   6           7   8   9   10  11  12
0  165  56   3  11190333.0   1   1   1  1551348.88   1   0   1   0   0

In [122]:
sample = scaler.transform(sample)

c:\Users\vssuj\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [123]:
pred_val = logi.predict(sample)

In [124]:
pred_val

array([1])

In [125]:
if pred_val == 1:
    print("Customer Exited")
else:
    print("Customer Not Exited")

Customer Exited