In [1]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, accuracy_score, precision_score,confusion_matrix

In [2]:
df = pd.read_csv("../datasets/Cleaned_Customer_Churn.csv")

In [3]:
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Gender_Female,Gender_Male,Geography_France,Geography_Germany,Geography_Spain,Exited
0,619,42,2,0.00,1,1,1,101348.88,1,0,1,0,0,1
1,608,41,1,83807.86,1,0,1,112542.58,1,0,0,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,1,0,0,1
3,699,39,1,0.00,2,0,0,93826.63,1,0,1,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,1,0,0,0,1,0

In [4]:
X = df.drop("Exited",axis=1)

In [5]:
Y = df['Exited']

In [6]:
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Gender_Female,Gender_Male,Geography_France,Geography_Germany,Geography_Spain
0,619,42,2,0.00,1,1,1,101348.88,1,0,1,0,0
1,608,41,1,83807.86,1,0,1,112542.58,1,0,0,0,1
2,502,42,8,159660.80,3,1,0,113931.57,1,0,1,0,0
3,699,39,1,0.00,2,0,0,93826.63,1,0,1,0,0
4,850,43,2,125510.82,1,1,1,79084.10,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,1,1,0,0
9996,516,35,10,57369.61,1,1,1,101699.77,0,1,1,0,0
9997,709,36,7,0.00,1,0,1,42085.58,1,0,1,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,0,1,0,1,0
9999,792,28,4,130142.79,1,1,0,38190.78,1,0,1,0,0

In [7]:
Y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [8]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.2,random_state=42,stratify=Y)

In [9]:
X_train

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Gender_Female,Gender_Male,Geography_France,Geography_Germany,Geography_Spain
2151,753,57,7,0.00,1,1,0,159475.08,0,1,1,0,0
8392,739,32,3,102128.27,1,1,0,63981.37,0,1,0,1,0
5006,755,37,0,113865.23,2,1,1,117396.25,1,0,0,1,0
4117,561,37,5,0.00,2,1,0,83093.25,0,1,1,0,0
7182,692,49,6,110540.43,2,0,1,107472.99,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4555,688,35,6,0.00,1,1,0,25488.43,1,0,0,0,1
4644,712,74,5,0.00,2,0,0,151425.82,0,1,0,0,1
8942,667,37,9,71786.90,2,1,1,67734.79,1,0,1,0,0
2935,687,35,8,100988.39,2,1,0,22247.27,0,1,0,0,1
6206,802,51,7,0.00,1,0,1,40855.79,0,1,0,0,1

In [10]:
DT = DecisionTreeClassifier()

In [11]:
DT.fit(X_train,Y_train)

DecisionTreeClassifier()

In [12]:
Y_pred = DT.predict(X_test)

In [13]:
Y_pred

array([0, 0, 0, ..., 1, 0, 0], shape=(2000,))

In [14]:
ypred = pd.DataFrame(Y_pred)

In [15]:
ypred.values_counts()

AttributeError: 'DataFrame' object has no attribute 'values_counts'

In [ ]:
accuracy_score(Y_test,Y_pred)

In [ ]:
print(classification_report(Y_test,Y_pred))